### ISSUE TITLE
Release version 1.1 - social features

### ISSUE THREAD

**Issue by buwilliams** [buwilliams/recifree#2]
## Roadmap

- [ ] Like or unlike recipe (must be logged-in)
- [ ] Message inbox
- [ ] Block and unblock user
- [ ] Compose message to user
- [ ] View all messages
- [ ] Mark message as read
- [ ] Archive message
- [ ] Search for message
- [ ] Sign-up: Facebook
- [ ] Sign-up: Email
- [ ] Sign-up: Instagram
- [ ] Sign-up: Gmail
